% This script allow to extract from a mvnx file generated by an acquisition 
% with the Xsens MVN all the data of interest:
% - location of the bony landmarks in the link reference frame
% - kinematics of each segment in term of position, orientation, linear and 
%   angular velocity and acceleration
% - joint angles

%clear all
%close all
%clc

subjectID=1;
tree=xml_read('C:\Users\Marta\Downloads\TESI\Bartender\Meri_1-Strap.mvnx');
save('tree');

format longg
nFrames = size(tree.subject.frames.frame,1);



%% Points Location 
% all the bony landmarks locations in the segments reference frame 

% Segment 1 - pelvis
pHipOriginLocation = tree.subject.segments.segment(1).points.point(1).pos_s;
pRightASILocation = tree.subject.segments.segment(1).points.point(7).pos_s;
pLeftASILocation = tree.subject.segments.segment(1).points.point(8).pos_s;
pRightCSILocation = tree.subject.segments.segment(1).points.point(9).pos_s;
pLeftCSILocation = tree.subject.segments.segment(1).points.point(10).pos_s;
pRightIschialTubLocation = tree.subject.segments.segment(1).points.point(11).pos_s;
pLeftIschialTubLocation = tree.subject.segments.segment(1).points.point(12).pos_s;
pSacrumLocation = tree.subject.segments.segment(1).points.point(13).pos_s;

% Segment 2 - L5
pL5SpinalProcessLocation = tree.subject.segments.segment(2).points.point(3).pos_s;

% Segment 3 - L3
pL3SpinalProcessLocation = tree.subject.segments.segment(3).points.point(3).pos_s;

% Segment 4 - T12
pT12SpinalProcessLocation = tree.subject.segments.segment(4).points.point(3).pos_s;

% Segment 5 - T8
pC7SpinalProcessLocation = tree.subject.segments.segment(5).points.point(5).pos_s; % also defined in segment 6 (neck)
pPXLocation = tree.subject.segments.segment(5).points.point(6).pos_s;
pIJLocation = tree.subject.segments.segment(5).points.point(7).pos_s; % also defined in segments 8 and 12 (right and left shoulder)
pT4SpinalProcessLocation = tree.subject.segments.segment(5).points.point(8).pos_s;
pT8SpinalProcessLocation = tree.subject.segments.segment(5).points.point(9).pos_s;

% Segment 7 - head
pTopOfHeadLocation = tree.subject.segments.segment(7).points.point(2).pos_s;
pRightAuricularisLocation = tree.subject.segments.segment(7).points.point(3).pos_s;
pLeftAuricularisLocation = tree.subject.segments.segment(7).points.point(4).pos_s;
pBackOfHeadLocation = tree.subject.segments.segment(7).points.point(5).pos_s;

% Segment 8 - rightShoulder
pRightAcromionLocation = tree.subject.segments.segment(8).points.point(4).pos_s;

% Segment 12 - leftShoulder
pLeftAcromionLocation = tree.subject.segments.segment(12).points.point(4).pos_s;

% Segment 9 - rightUpperArm
pRightArmLatEpicondyleLocation = tree.subject.segments.segment(9).points.point(3).pos_s;
pRightArmMedEpicondyleLocation = tree.subject.segments.segment(9).points.point(4).pos_s;

% Segment 13 - leftUpperArm
pLeftArmLatEpicondyleLocation = tree.subject.segments.segment(13).points.point(3).pos_s;
pLeftArmMedEpicondyleLocation = tree.subject.segments.segment(13).points.point(4).pos_s;

% Segment 10 - rightForeArm
pRightUlnarStyloidLocation  = tree.subject.segments.segment(10).points.point(3).pos_s;
pRightRadialStyloidLocation  = tree.subject.segments.segment(10).points.point(4).pos_s;
pRightOlecranonLocation  = tree.subject.segments.segment(10).points.point(5).pos_s;

% Segment 14 - leftForeArm
pLeftUlnarStyloidLocation  = tree.subject.segments.segment(14).points.point(3).pos_s;
pLeftRadialStyloidLocation  = tree.subject.segments.segment(14).points.point(4).pos_s;
pLeftOlecranonLocation  = tree.subject.segments.segment(14).points.point(5).pos_s;

% Segment 11 - rightHand
pRightTopOfHandLocation  = tree.subject.segments.segment(11).points.point(2).pos_s;
pRightPinkyLocation  = tree.subject.segments.segment(11).points.point(3).pos_s;
pRightBallHandLocation  = tree.subject.segments.segment(11).points.point(4).pos_s;

% Segment 15 - leftHand
pLeftTopOfHandLocation  = tree.subject.segments.segment(15).points.point(2).pos_s;
pLeftPinkyLocation  = tree.subject.segments.segment(15).points.point(3).pos_s;
pLeftBallHandLocation  = tree.subject.segments.segment(15).points.point(4).pos_s;

% Segment 16 - rightUpperLeg
pRightGreaterTrochanterLocation  = tree.subject.segments.segment(16).points.point(3).pos_s;
pRightPatellaLocation  = tree.subject.segments.segment(16).points.point(6).pos_s; 

% Segment 17 - rightLowerLeg
pRightKneeLatEpicondyleLocation  = tree.subject.segments.segment(17).points.point(3).pos_s; % also defined in segment 16 (right upper leg)
pRightKneeMedEpicondyleLocation  = tree.subject.segments.segment(17).points.point(4).pos_s; % also defined in segment 16 (right upper leg)
pRightLatMalleolusLocation  = tree.subject.segments.segment(17).points.point(5).pos_s;
pRightMedMalleolusLocation  = tree.subject.segments.segment(17).points.point(6).pos_s;
pRightTibialTubLocation  = tree.subject.segments.segment(17).points.point(7).pos_s;

% Segment 20 - leftUpperLeg
pLeftGreaterTrochanterLocation  = tree.subject.segments.segment(20).points.point(3).pos_s; 
pLeftPatellaLocation  = tree.subject.segments.segment(20).points.point(6).pos_s; 

% Segment 21 - leftLowerLeg
pLeftKneeLatEpicondyleLocation  = tree.subject.segments.segment(21).points.point(3).pos_s; % also defined in segment 20 (left upper leg)
pLeftKneeMedEpicondyleLocation  = tree.subject.segments.segment(21).points.point(4).pos_s; % also defined in segment 20 (left upper leg)
pLeftLatMalleolusLocation  = tree.subject.segments.segment(21).points.point(5).pos_s;
pLeftMedMalleolusLocation  = tree.subject.segments.segment(21).points.point(6).pos_s;
pLeftTibialTubLocation  = tree.subject.segments.segment(21).points.point(7).pos_s;

% Segment 18 - rightFoot
pRightHeelFootLocation  = tree.subject.segments.segment(18).points.point(3).pos_s;
pRightFirstMetatarsalLocation  = tree.subject.segments.segment(18).points.point(4).pos_s;
pRightFifthMetatarsalLocation  = tree.subject.segments.segment(18).points.point(5).pos_s;
pRightPivotFootLocation  = tree.subject.segments.segment(18).points.point(6).pos_s;
pRightHeelCenterLocation  = tree.subject.segments.segment(18).points.point(7).pos_s;

% Segment 19 - rightToe
pRightToeLocation  = tree.subject.segments.segment(19).points.point(2).pos_s;

% Segment 22 - leftFoot
pLeftHeelFootLocation  = tree.subject.segments.segment(22).points.point(3).pos_s;
pLeftFirstMetatarsalLocation  = tree.subject.segments.segment(22).points.point(4).pos_s;
pLeftFifthMetatarsalLocation  = tree.subject.segments.segment(22).points.point(5).pos_s;
pLeftPivotFootLocation  = tree.subject.segments.segment(22).points.point(6).pos_s;
pLeftHeelCenterLocation  = tree.subject.segments.segment(22).points.point(7).pos_s;

% Segment 23 - leftToe
pLeftToeLocation  = tree.subject.segments.segment(23).points.point(2).pos_s;


%% Orientation and position of the origin of the 23 segments
% espressed in the global reference frame

% Orientation

for i = 1 : nFrames
    pelvisOrientation(i,1:4) = tree.subject.frames.frame(i).orientation(1:4);
    l5Orientation(i,1:4) = tree.subject.frames.frame(i).orientation(5:8);
    l3Orientation(i,1:4) = tree.subject.frames.frame(i).orientation(9:12);
    t12Orientation(i,1:4) = tree.subject.frames.frame(i).orientation(13:16);
    t8Orientation(i,1:4) = tree.subject.frames.frame(i).orientation(17:20);
    neckOrientation(i,1:4) = tree.subject.frames.frame(i).orientation(21:24);
    headOrientation(i,1:4) = tree.subject.frames.frame(i).orientation(25:28);
    rightShoulderOrientation(i,1:4) = tree.subject.frames.frame(i).orientation(29:32);
    rightUpperArmOrientation(i,1:4) = tree.subject.frames.frame(i).orientation(33:36);
    rightForeArmOrientation(i,1:4) = tree.subject.frames.frame(i).orientation(37:40);
    rightHandOrientation(i,1:4) = tree.subject.frames.frame(i).orientation(41:44);
    leftShoulderOrientation(i,1:4) = tree.subject.frames.frame(i).orientation(45:48);
    leftUpperArmOrientation(i,1:4) = tree.subject.frames.frame(i).orientation(49:52);
    leftForeArmOrientation(i,1:4) = tree.subject.frames.frame(i).orientation(53:56);
    leftHandOrientation(i,1:4) = tree.subject.frames.frame(i).orientation(57:60);
    rightUpperLegOrientation(i,1:4) = tree.subject.frames.frame(i).orientation(61:64);
    rightLowerLegOrientation(i,1:4) = tree.subject.frames.frame(i).orientation(65:68);
    rightFootOrientation(i,1:4) = tree.subject.frames.frame(i).orientation(69:72);
    rightToeOrientation(i,1:4) = tree.subject.frames.frame(i).orientation(73:76);
    leftUpperLegOrientation(i,1:4) = tree.subject.frames.frame(i).orientation(77:80);
    leftLowerLegOrientation(i,1:4) = tree.subject.frames.frame(i).orientation(81:84);
    leftFootOrientation(i,1:4) = tree.subject.frames.frame(i).orientation(85:88);
    leftToeOrientation(i,1:4) = tree.subject.frames.frame(i).orientation(89:92);
end

% Position

for i = 1 : nFrames
    pelvisPosition(i,1:3) = tree.subject.frames.frame(i).position(1:3);
    l5Position(i,1:3) = tree.subject.frames.frame(i).position(4:6);
    l3Position(i,1:3) = tree.subject.frames.frame(i).position(7:9);
    t12Position(i,1:3) = tree.subject.frames.frame(i).position(10:12);
    t8Position(i,1:3) = tree.subject.frames.frame(i).position(13:15);
    neckPosition(i,1:3) = tree.subject.frames.frame(i).position(16:18);
    headPosition(i,1:3) = tree.subject.frames.frame(i).position(19:21);
    rightShoulderPosition(i,1:3) = tree.subject.frames.frame(i).position(22:24);
    rightUpperArmPosition(i,1:3) = tree.subject.frames.frame(i).position(25:27);
    rightForeArmPosition(i,1:3) = tree.subject.frames.frame(i).position(28:30);
    rightHandPosition(i,1:3) = tree.subject.frames.frame(i).position(31:33);
    leftShoulderPosition(i,1:3) = tree.subject.frames.frame(i).position(34:36);
    leftUpperArmPosition(i,1:3) = tree.subject.frames.frame(i).position(37:39);
    leftForeArmPosition(i,1:3) = tree.subject.frames.frame(i).position(40:42);
    leftHandPosition(i,1:3) = tree.subject.frames.frame(i).position(43:45);
    rightUpperLegPosition(i,1:3) = tree.subject.frames.frame(i).position(46:48);
    rightLowerLegPosition(i,1:3) = tree.subject.frames.frame(i).position(49:51);
    rightFootPosition(i,1:3) = tree.subject.frames.frame(i).position(52:54);
    rightToePosition(i,1:3) = tree.subject.frames.frame(i).position(55:57);
    leftUpperLegPosition(i,1:3) = tree.subject.frames.frame(i).position(58:60);
    leftLowerLegPosition(i,1:3) = tree.subject.frames.frame(i).position(61:63);
    leftFootPosition(i,1:3) = tree.subject.frames.frame(i).position(64:66);
    leftToePosition(i,1:3) = tree.subject.frames.frame(i).position(67:69);
end

%% Linear and angular velocity of the origin of the 23 segments
% espressed in the global reference frame

% Linear Velocity

for i = 3 : nFrames
    pelvisVelocity(i,1:3) = tree.subject.frames.frame(i).velocity(1:3);
    l5Velocity(i,1:3) = tree.subject.frames.frame(i).velocity(4:6);
    l3Velocity(i,1:3) = tree.subject.frames.frame(i).velocity(7:9);
    t12Velocity(i,1:3) = tree.subject.frames.frame(i).velocity(10:12);
    t8Velocity(i,1:3) = tree.subject.frames.frame(i).velocity(13:15);
    neckVelocity(i,1:3) = tree.subject.frames.frame(i).velocity(16:18);
    headVelocity(i,1:3) = tree.subject.frames.frame(i).velocity(19:21);
    rightShoulderVelocity(i,1:3) = tree.subject.frames.frame(i).velocity(22:24);
    rightUpperArmVelocity(i,1:3) = tree.subject.frames.frame(i).velocity(25:27);
    rightForeArmVelocity(i,1:3) = tree.subject.frames.frame(i).velocity(28:30);
    rightHandVelocity(i,1:3) = tree.subject.frames.frame(i).velocity(31:33);
    leftShoulderVelocity(i,1:3) = tree.subject.frames.frame(i).velocity(34:36);
    leftUpperArmVelocity(i,1:3) = tree.subject.frames.frame(i).velocity(37:39);
    leftForeArmVelocity(i,1:3) = tree.subject.frames.frame(i).velocity(40:42);
    leftHandVelocity(i,1:3) = tree.subject.frames.frame(i).velocity(43:45);
    rightUpperLegVelocity(i,1:3) = tree.subject.frames.frame(i).velocity(46:48);
    rightLowerLegVelocity(i,1:3) = tree.subject.frames.frame(i).velocity(49:51);
    rightFootVelocity(i,1:3) = tree.subject.frames.frame(i).velocity(52:54);
    rightToeVelocity(i,1:3) = tree.subject.frames.frame(i).velocity(55:57);
    leftUpperLegVelocity(i,1:3) = tree.subject.frames.frame(i).velocity(58:60);
    leftLowerLegVelocity(i,1:3) = tree.subject.frames.frame(i).velocity(61:63);
    leftFootVelocity(i,1:3) = tree.subject.frames.frame(i).velocity(64:66);
    leftToeVelocity(i,1:3) = tree.subject.frames.frame(i).velocity(67:69);
end

% Angular Velocity

for i = 3 : nFrames
    pelvisAngularVelocity(i,1:3) = tree.subject.frames.frame(i).angularVelocity(1:3);
    l5AngularVelocity(i,1:3) = tree.subject.frames.frame(i).angularVelocity(4:6);
    l3AngularVelocity(i,1:3) = tree.subject.frames.frame(i).angularVelocity(7:9);
    t12AngularVelocity(i,1:3) = tree.subject.frames.frame(i).angularVelocity(10:12);
    t8AngularVelocity(i,1:3) = tree.subject.frames.frame(i).angularVelocity(13:15);
    neckAngularVelocity(i,1:3) = tree.subject.frames.frame(i).angularVelocity(16:18);
    headAngularVelocity(i,1:3) = tree.subject.frames.frame(i).angularVelocity(19:21);
    rightShoulderAngularVelocity(i,1:3) = tree.subject.frames.frame(i).angularVelocity(22:24);
    rightUpperArmAngularVelocity(i,1:3) = tree.subject.frames.frame(i).angularVelocity(25:27);
    rightForeArmAngularVelocity(i,1:3) = tree.subject.frames.frame(i).angularVelocity(28:30);
    rightHandAngularVelocity(i,1:3) = tree.subject.frames.frame(i).angularVelocity(31:33);
    leftShoulderAngularVelocity(i,1:3) = tree.subject.frames.frame(i).angularVelocity(34:36);
    leftUpperArmAngularVelocity(i,1:3) = tree.subject.frames.frame(i).angularVelocity(37:39);
    leftForeArmAngularVelocity(i,1:3) = tree.subject.frames.frame(i).angularVelocity(40:42);
    leftHandAngularVelocity(i,1:3) = tree.subject.frames.frame(i).angularVelocity(43:45);
    rightUpperLegAngularVelocity(i,1:3) = tree.subject.frames.frame(i).angularVelocity(46:48);
    rightLowerLegAngularVelocity(i,1:3) = tree.subject.frames.frame(i).angularVelocity(49:51);
    rightFootAngularVelocity(i,1:3) = tree.subject.frames.frame(i).angularVelocity(52:54);
    rightToeAngularVelocity(i,1:3) = tree.subject.frames.frame(i).angularVelocity(55:57);
    leftUpperLegAngularVelocity(i,1:3) = tree.subject.frames.frame(i).angularVelocity(58:60);
    leftLowerLegAngularVelocity(i,1:3) = tree.subject.frames.frame(i).angularVelocity(61:63);
    leftFootAngularVelocity(i,1:3) = tree.subject.frames.frame(i).angularVelocity(64:66);
    leftToeAngularVelocity(i,1:3) = tree.subject.frames.frame(i).angularVelocity(67:69);
end

%% Linear and angular acceleration of the origin of the 23 segments
% espressed in the global reference frame

% Linear acceleration

for i = 3 : nFrames
    pelvisAcceleration(i,1:3) = tree.subject.frames.frame(i).acceleration(1:3);
    l5Acceleration(i,1:3) = tree.subject.frames.frame(i).acceleration(4:6);
    l3Acceleration(i,1:3) = tree.subject.frames.frame(i).acceleration(7:9);
    t12Acceleration(i,1:3) = tree.subject.frames.frame(i).acceleration(10:12);
    t8Acceleration(i,1:3) = tree.subject.frames.frame(i).acceleration(13:15);
    neckAcceleration(i,1:3) = tree.subject.frames.frame(i).acceleration(16:18);
    headAcceleration(i,1:3) = tree.subject.frames.frame(i).acceleration(19:21);
    rightShoulderAcceleration(i,1:3) = tree.subject.frames.frame(i).acceleration(22:24);
    rightUpperArmAcceleration(i,1:3) = tree.subject.frames.frame(i).acceleration(25:27);
    rightForeArmAcceleration(i,1:3) = tree.subject.frames.frame(i).acceleration(28:30);
    rightHandAcceleration(i,1:3) = tree.subject.frames.frame(i).acceleration(31:33);
    leftShoulderAcceleration(i,1:3) = tree.subject.frames.frame(i).acceleration(34:36);
    leftUpperArmAcceleration(i,1:3) = tree.subject.frames.frame(i).acceleration(37:39);
    leftForeArmAcceleration(i,1:3) = tree.subject.frames.frame(i).acceleration(40:42);
    leftHandAcceleration(i,1:3) = tree.subject.frames.frame(i).acceleration(43:45);
    rightUpperLegAcceleration(i,1:3) = tree.subject.frames.frame(i).acceleration(46:48);
    rightLowerLegAcceleration(i,1:3) = tree.subject.frames.frame(i).acceleration(49:51);
    rightFootAcceleration(i,1:3) = tree.subject.frames.frame(i).acceleration(52:54);
    rightToeAcceleration(i,1:3) = tree.subject.frames.frame(i).acceleration(55:57);
    leftUpperLegAcceleration(i,1:3) = tree.subject.frames.frame(i).acceleration(58:60);
    leftLowerLegAcceleration(i,1:3) = tree.subject.frames.frame(i).acceleration(61:63);
    leftFootAcceleration(i,1:3) = tree.subject.frames.frame(i).acceleration(64:66);
    leftToeAcceleration(i,1:3) = tree.subject.frames.frame(i).acceleration(67:69);
end

% Angular acceleration

for i = 3 : nFrames
    pelvisAngularAcceleration(i,1:3) = tree.subject.frames.frame(i).angularAcceleration(1:3);
    l5AngularAcceleration(i,1:3) = tree.subject.frames.frame(i).angularAcceleration(4:6);
    l3AngularAcceleration(i,1:3) = tree.subject.frames.frame(i).angularAcceleration(7:9);
    t12AngularAcceleration(i,1:3) = tree.subject.frames.frame(i).angularAcceleration(10:12);
    t8AngularAcceleration(i,1:3) = tree.subject.frames.frame(i).angularAcceleration(13:15);
    neckAngularAcceleration(i,1:3) = tree.subject.frames.frame(i).angularAcceleration(16:18);
    headAngularAcceleration(i,1:3) = tree.subject.frames.frame(i).angularAcceleration(19:21);
    rightShoulderAngularAcceleration(i,1:3) = tree.subject.frames.frame(i).angularAcceleration(22:24);
    rightUpperArmAngularAcceleration(i,1:3) = tree.subject.frames.frame(i).angularAcceleration(25:27);
    rightForeArmAngularAcceleration(i,1:3) = tree.subject.frames.frame(i).angularAcceleration(28:30);
    rightHandAngularAcceleration(i,1:3) = tree.subject.frames.frame(i).angularAcceleration(31:33);
    leftShoulderAngularAcceleration(i,1:3) = tree.subject.frames.frame(i).angularAcceleration(34:36);
    leftUpperArmAngularAcceleration(i,1:3) = tree.subject.frames.frame(i).angularAcceleration(37:39);
    leftForeArmAngularAcceleration(i,1:3) = tree.subject.frames.frame(i).angularAcceleration(40:42);
    leftHandAngularAcceleration(i,1:3) = tree.subject.frames.frame(i).angularAcceleration(43:45);
    rightUpperLegAngularAcceleration(i,1:3) = tree.subject.frames.frame(i).angularAcceleration(46:48);
    rightLowerLegAngularAcceleration(i,1:3) = tree.subject.frames.frame(i).angularAcceleration(49:51);
    rightFootAngularAcceleration(i,1:3) = tree.subject.frames.frame(i).angularAcceleration(52:54);
    rightToeAngularAcceleration(i,1:3) = tree.subject.frames.frame(i).angularAcceleration(55:57);
    leftUpperLegAngularAcceleration(i,1:3) = tree.subject.frames.frame(i).angularAcceleration(58:60);
    leftLowerLegAngularAcceleration(i,1:3) = tree.subject.frames.frame(i).angularAcceleration(61:63);
    leftFootAngularAcceleration(i,1:3) = tree.subject.frames.frame(i).angularAcceleration(64:66);
    leftToeAngularAcceleration(i,1:3) = tree.subject.frames.frame(i).angularAcceleration(67:69);
end

%% Joint angles 
% espressed in two different notation

% JointAngle

for i = 3 : nFrames
    jL5S1JointAngle(i,1:3) = tree.subject.frames.frame(i).jointAngle(1:3);
    jL4L3JointAngle(i,1:3) = tree.subject.frames.frame(i).jointAngle(4:6);
    jL1T12JointAngle(i,1:3) = tree.subject.frames.frame(i).jointAngle(7:9);
    jT9T8JointAngle(i,1:3) = tree.subject.frames.frame(i).jointAngle(10:12);
    jT1C7JointAngle(i,1:3) = tree.subject.frames.frame(i).jointAngle(13:15);
    jC1HeadJointAngle(i,1:3) = tree.subject.frames.frame(i).jointAngle(16:18);
    jRightC7ShoulderJointAngle(i,1:3) = tree.subject.frames.frame(i).jointAngle(19:21);
    jRightShoulderJointAngle(i,1:3) = tree.subject.frames.frame(i).jointAngle(22:24);
    jRightElbowJointAngle(i,1:3) = tree.subject.frames.frame(i).jointAngle(25:27);
    jRightWristJointAngle(i,1:3) = tree.subject.frames.frame(i).jointAngle(28:30);
    jLeftC7ShoulderJointAngle(i,1:3) = tree.subject.frames.frame(i).jointAngle(31:33);
    jLeftShoulderJointAngle(i,1:3) = tree.subject.frames.frame(i).jointAngle(34:36);
    jLeftElbowJointAngle(i,1:3) = tree.subject.frames.frame(i).jointAngle(37:39);
    jLeftWristJointAngle(i,1:3) = tree.subject.frames.frame(i).jointAngle(40:42);
    jRightHipJointAngle(i,1:3) = tree.subject.frames.frame(i).jointAngle(43:45);
    jRightKneeJointAngle(i,1:3) = tree.subject.frames.frame(i).jointAngle(46:48);
    jRightAnkleJointAngle(i,1:3) = tree.subject.frames.frame(i).jointAngle(49:51);
    jRightBallFootJointAngle(i,1:3) = tree.subject.frames.frame(i).jointAngle(52:54);
    jLeftHipJointAngle(i,1:3) = tree.subject.frames.frame(i).jointAngle(55:57);
    jLeftKneeJointAngle(i,1:3) = tree.subject.frames.frame(i).jointAngle(58:60);
    jLeftAnkleJointAngle(i,1:3) = tree.subject.frames.frame(i).jointAngle(61:63);
    jLeftBallFootJointAngle(i,1:3) = tree.subject.frames.frame(i).jointAngle(64:66);
end

% JointAngleXZY

for i = 3 : nFrames
    jL5S1JointAngleXZY(i,1:3) = tree.subject.frames.frame(i).jointAngleXZY(1:3);
    jL4L3JointAngleXZY(i,1:3) = tree.subject.frames.frame(i).jointAngleXZY(4:6);
    jL1T12JointAngleXZY(i,1:3) = tree.subject.frames.frame(i).jointAngleXZY(7:9);
    jT9T8JointAngleXZY(i,1:3) = tree.subject.frames.frame(i).jointAngleXZY(10:12);
    jT1C7JointAngleXZY(i,1:3) = tree.subject.frames.frame(i).jointAngleXZY(13:15);
    jC1HeadJointAngleXZY(i,1:3) = tree.subject.frames.frame(i).jointAngleXZY(16:18);
    jRightC7ShoulderJointAngleXZY(i,1:3) = tree.subject.frames.frame(i).jointAngleXZY(19:21);
    jRightShoulderJointAngleXZY(i,1:3) = tree.subject.frames.frame(i).jointAngleXZY(22:24);
    jRightElbowJointAngleXZY(i,1:3) = tree.subject.frames.frame(i).jointAngleXZY(25:27);
    jRightWristJointAngleXZY(i,1:3) = tree.subject.frames.frame(i).jointAngleXZY(28:30);
    jLeftC7ShoulderJointAngleXZY(i,1:3) = tree.subject.frames.frame(i).jointAngleXZY(31:33);
    jLeftShoulderJointAngleXZY(i,1:3) = tree.subject.frames.frame(i).jointAngleXZY(34:36);
    jLeftElbowJointAngleXZY(i,1:3) = tree.subject.frames.frame(i).jointAngleXZY(37:39);
    jLeftWristJointAngleXZY(i,1:3) = tree.subject.frames.frame(i).jointAngleXZY(40:42);
    jRightHipJointAngleXZY(i,1:3) = tree.subject.frames.frame(i).jointAngleXZY(43:45);
    jRightKneeJointAngleXZY(i,1:3) = tree.subject.frames.frame(i).jointAngleXZY(46:48);
    jRightAnkleJointAngleXZY(i,1:3) = tree.subject.frames.frame(i).jointAngleXZY(49:51);
    jRightBallFootJointAngleXZY(i,1:3) = tree.subject.frames.frame(i).jointAngleXZY(52:54);
    jLeftHipJointAngleXZY(i,1:3) = tree.subject.frames.frame(i).jointAngleXZY(55:57);
    jLeftKneeJointAngleXZY(i,1:3) = tree.subject.frames.frame(i).jointAngleXZY(58:60);
    jLeftAnkleJointAngleXZY(i,1:3) = tree.subject.frames.frame(i).jointAngleXZY(61:63);
    jLeftBallFootJointAngleXZY(i,1:3) = tree.subject.frames.frame(i).jointAngleXZY(64:66);
end

%% Saving all the variables

% Points location

pointsLocation(subjectID).pHipOriginLocation = pHipOriginLocation;
pointsLocation(subjectID).pRightASILocation = pRightASILocation;
pointsLocation(subjectID).pLeftASILocation = pLeftASILocation;
pointsLocation(subjectID).pRightCSILocation = pRightCSILocation;
pointsLocation(subjectID).pLeftCSILocation = pLeftCSILocation;
pointsLocation(subjectID).pRightIschialTubLocation = pRightIschialTubLocation;
pointsLocation(subjectID).pLeftIschialTubLocation = pLeftIschialTubLocation;
pointsLocation(subjectID).pSacrumLocation = pSacrumLocation;
pointsLocation(subjectID).pL5SpinalProcessLocation = pL5SpinalProcessLocation;
pointsLocation(subjectID).pL3SpinalProcessLocation = pL3SpinalProcessLocation;
pointsLocation(subjectID).pT12SpinalProcessLocation = pT12SpinalProcessLocation;
pointsLocation(subjectID).pPXLocation = pPXLocation;
pointsLocation(subjectID).pIJLocation = pIJLocation;
pointsLocation(subjectID).pT4SpinalProcessLocation = pT4SpinalProcessLocation;
pointsLocation(subjectID).pT8SpinalProcessLocation = pT8SpinalProcessLocation;
pointsLocation(subjectID).pC7SpinalProcessLocation = pC7SpinalProcessLocation;
pointsLocation(subjectID).pTopOfHeadLocation = pTopOfHeadLocation;
pointsLocation(subjectID).pRightAuricularisLocation = pRightAuricularisLocation;
pointsLocation(subjectID).pLeftAuricularisLocation = pLeftAuricularisLocation;
pointsLocation(subjectID).pBackOfHeadLocation = pBackOfHeadLocation;

pointsLocation(subjectID).pRightAcromionLocation = pRightAcromionLocation;
pointsLocation(subjectID).pLeftAcromionLocation = pLeftAcromionLocation;
pointsLocation(subjectID).pRightArmLatEpicondyleLocation = pRightArmLatEpicondyleLocation;
pointsLocation(subjectID).pRightArmMedEpicondyleLocation = pRightArmMedEpicondyleLocation;
pointsLocation(subjectID).pLeftArmLatEpicondyleLocation = pLeftArmLatEpicondyleLocation;
pointsLocation(subjectID).pLeftArmMedEpicondyleLocation = pLeftArmMedEpicondyleLocation;
pointsLocation(subjectID).pRightUlnarStyloidLocation = pRightUlnarStyloidLocation;
pointsLocation(subjectID).pRightRadialStyloidLocation = pRightRadialStyloidLocation;
pointsLocation(subjectID).pRightOlecranonLocation = pRightOlecranonLocation;
pointsLocation(subjectID).pLeftUlnarStyloidLocation = pLeftUlnarStyloidLocation;
pointsLocation(subjectID).pLeftRadialStyloidLocation = pLeftRadialStyloidLocation;
pointsLocation(subjectID).pLeftOlecranonLocation = pLeftOlecranonLocation;
pointsLocation(subjectID).pRightTopOfHandLocation = pRightTopOfHandLocation;
pointsLocation(subjectID).pRightPinkyLocation = pRightPinkyLocation;
pointsLocation(subjectID).pRightBallHandLocation = pRightBallHandLocation;
pointsLocation(subjectID).pLeftTopOfHandLocation = pLeftTopOfHandLocation;
pointsLocation(subjectID).pLeftPinkyLocation = pLeftPinkyLocation;
pointsLocation(subjectID).pLeftBallHandLocation = pLeftBallHandLocation;

pointsLocation(subjectID).pRightGreaterTrochanterLocation = pRightGreaterTrochanterLocation;
pointsLocation(subjectID).pRightKneeLatEpicondyleLocation = pRightKneeLatEpicondyleLocation;
pointsLocation(subjectID).pRightKneeMedEpicondyleLocation = pRightKneeMedEpicondyleLocation;
pointsLocation(subjectID).pRightPatellaLocation = pRightPatellaLocation;
pointsLocation(subjectID).pLeftGreaterTrochanterLocation = pLeftGreaterTrochanterLocation;
pointsLocation(subjectID).pLeftKneeLatEpicondyleLocation = pLeftKneeLatEpicondyleLocation;
pointsLocation(subjectID).pLeftKneeMedEpicondyleLocation = pLeftKneeMedEpicondyleLocation;
pointsLocation(subjectID).pLeftPatellaLocation = pLeftPatellaLocation;
pointsLocation(subjectID).pRightLatMalleolusLocation = pRightLatMalleolusLocation;
pointsLocation(subjectID).pRightMedMalleolusLocation = pRightMedMalleolusLocation;
pointsLocation(subjectID).pRightTibialTubLocation = pRightTibialTubLocation;
pointsLocation(subjectID).pLeftLatMalleolusLocation = pLeftLatMalleolusLocation;
pointsLocation(subjectID).pLeftMedMalleolusLocation = pLeftMedMalleolusLocation;
pointsLocation(subjectID).pLeftTibialTubLocation = pLeftTibialTubLocation;
pointsLocation(subjectID).pRightHeelFootLocation = pRightHeelFootLocation;
pointsLocation(subjectID).pRightFirstMetatarsalLocation = pRightFirstMetatarsalLocation;
pointsLocation(subjectID).pRightFifthMetatarsalLocation = pRightFifthMetatarsalLocation;
pointsLocation(subjectID).pRightPivotFootLocation = pRightPivotFootLocation;
pointsLocation(subjectID).pRightHeelCenterLocation = pRightHeelCenterLocation;
pointsLocation(subjectID).pRightToeLocation = pRightToeLocation;
pointsLocation(subjectID).pLeftHeelFootLocation = pLeftHeelFootLocation;
pointsLocation(subjectID).pLeftFirstMetatarsalLocation = pLeftFirstMetatarsalLocation;
pointsLocation(subjectID).pLeftFifthMetatarsalLocation = pLeftFifthMetatarsalLocation;
pointsLocation(subjectID).pLeftPivotFootLocation = pLeftPivotFootLocation;
pointsLocation(subjectID).pLeftHeelCenterLocation = pLeftHeelCenterLocation;
pointsLocation(subjectID).pLeftToeLocation = pLeftToeLocation;

% Segment kinematics

pelvisKinematics(subjectID).orientation = pelvisOrientation;
pelvisKinematics(subjectID).position = pelvisPosition;
pelvisKinematics(subjectID).velocity = pelvisVelocity;
pelvisKinematics(subjectID).angularVelocity = pelvisAngularVelocity;
pelvisKinematics(subjectID).acceleration = pelvisAcceleration;
pelvisKinematics(subjectID).angularAcceleration = pelvisAngularAcceleration;

l5Kinematics(subjectID).orientation = l5Orientation;
l5Kinematics(subjectID).position = l5Position;
l5Kinematics(subjectID).velocity = l5Velocity;
l5Kinematics(subjectID).angularVelocity = l5AngularVelocity;
l5Kinematics(subjectID).acceleration = l5Acceleration;
l5Kinematics(subjectID).angularAcceleration = l5AngularAcceleration;

l3Kinematics(subjectID).orientation = l3Orientation;
l3Kinematics(subjectID).position = l3Position;
l3Kinematics(subjectID).velocity = l3Velocity;
l3Kinematics(subjectID).angularVelocity = l3AngularVelocity;
l3Kinematics(subjectID).acceleration = l3Acceleration;
l3Kinematics(subjectID).angularAcceleration = l3AngularAcceleration;

t12Kinematics(subjectID).orientation = t12Orientation;
t12Kinematics(subjectID).position = t12Position;
t12Kinematics(subjectID).velocity = t12Velocity;
t12Kinematics(subjectID).angularVelocity = t12AngularVelocity;
t12Kinematics(subjectID).acceleration = t12Acceleration;
t12Kinematics(subjectID).angularAcceleration = t12AngularAcceleration;

t8Kinematics(subjectID).orientation = t8Orientation;
t8Kinematics(subjectID).position = t8Position;
t8Kinematics(subjectID).velocity = t8Velocity;
t8Kinematics(subjectID).angularVelocity = t8AngularVelocity;
t8Kinematics(subjectID).acceleration = t8Acceleration;
t8Kinematics(subjectID).angularAcceleration = t8AngularAcceleration;

neckKinematics(subjectID).orientation = neckOrientation;
neckKinematics(subjectID).position = neckPosition;
neckKinematics(subjectID).velocity = neckVelocity;
neckKinematics(subjectID).angularVelocity = neckAngularVelocity;
neckKinematics(subjectID).acceleration = neckAcceleration;
neckKinematics(subjectID).angularAcceleration = neckAngularAcceleration;

headKinematics(subjectID).orientation = headOrientation;
headKinematics(subjectID).position = headPosition;
headKinematics(subjectID).velocity = headVelocity;
headKinematics(subjectID).angularVelocity = headAngularVelocity;
headKinematics(subjectID).acceleration = headAcceleration;
headKinematics(subjectID).angularAcceleration = headAngularAcceleration;

rightShoulderKinematics(subjectID).orientation = rightShoulderOrientation;
rightShoulderKinematics(subjectID).position = rightShoulderPosition;
rightShoulderKinematics(subjectID).velocity = rightShoulderVelocity;
rightShoulderKinematics(subjectID).angularVelocity = rightShoulderAngularVelocity;
rightShoulderKinematics(subjectID).acceleration = rightShoulderAcceleration;
rightShoulderKinematics(subjectID).angularAcceleration = rightShoulderAngularAcceleration;

rightUpperArmKinematics(subjectID).orientation = rightUpperArmOrientation;
rightUpperArmKinematics(subjectID).position = rightUpperArmPosition;
rightUpperArmKinematics(subjectID).velocity = rightUpperArmVelocity;
rightUpperArmKinematics(subjectID).angularVelocity = rightUpperArmAngularVelocity;
rightUpperArmKinematics(subjectID).acceleration = rightUpperArmAcceleration;
rightUpperArmKinematics(subjectID).angularAcceleration = rightUpperArmAngularAcceleration;

rightForeArmKinematics(subjectID).orientation = rightForeArmOrientation;
rightForeArmKinematics(subjectID).position = rightForeArmPosition;
rightForeArmKinematics(subjectID).velocity = rightForeArmVelocity;
rightForeArmKinematics(subjectID).angularVelocity = rightForeArmAngularVelocity;
rightForeArmKinematics(subjectID).acceleration = rightForeArmAcceleration;
rightForeArmKinematics(subjectID).angularAcceleration = rightForeArmAngularAcceleration;

rightHandKinematics(subjectID).orientation = rightHandOrientation;
rightHandKinematics(subjectID).position = rightHandPosition;
rightHandKinematics(subjectID).velocity = rightHandVelocity;
rightHandKinematics(subjectID).angularVelocity = rightHandAngularVelocity;
rightHandKinematics(subjectID).acceleration = rightHandAcceleration;
rightHandKinematics(subjectID).angularAcceleration = rightHandAngularAcceleration;

leftShoulderKinematics(subjectID).orientation = leftShoulderOrientation;
leftShoulderKinematics(subjectID).position = leftShoulderPosition;
leftShoulderKinematics(subjectID).velocity = leftShoulderVelocity;
leftShoulderKinematics(subjectID).angularVelocity = leftShoulderAngularVelocity;
leftShoulderKinematics(subjectID).acceleration = leftShoulderAcceleration;
leftShoulderKinematics(subjectID).angularAcceleration = leftShoulderAngularAcceleration;

leftUpperArmKinematics(subjectID).orientation = leftUpperArmOrientation;
leftUpperArmKinematics(subjectID).position = leftUpperArmPosition;
leftUpperArmKinematics(subjectID).velocity = leftUpperArmVelocity;
leftUpperArmKinematics(subjectID).angularVelocity = leftUpperArmAngularVelocity;
leftUpperArmKinematics(subjectID).acceleration = leftUpperArmAcceleration;
leftUpperArmKinematics(subjectID).angularAcceleration = leftUpperArmAngularAcceleration;

leftForeArmKinematics(subjectID).orientation = leftForeArmOrientation;
leftForeArmKinematics(subjectID).position = leftForeArmPosition;
leftForeArmKinematics(subjectID).velocity = leftForeArmVelocity;
leftForeArmKinematics(subjectID).angularVelocity = leftForeArmAngularVelocity;
leftForeArmKinematics(subjectID).acceleration = leftForeArmAcceleration;
leftForeArmKinematics(subjectID).angularAcceleration = leftForeArmAngularAcceleration;

leftHandKinematics(subjectID).orientation = leftHandOrientation;
leftHandKinematics(subjectID).position = leftHandPosition;
leftHandKinematics(subjectID).velocity = leftHandVelocity;
leftHandKinematics(subjectID).angularVelocity = leftHandAngularVelocity;
leftHandKinematics(subjectID).acceleration = leftHandAcceleration;
leftHandKinematics(subjectID).angularAcceleration = leftHandAngularAcceleration;

rightUpperLegKinematics(subjectID).orientation = rightUpperLegOrientation;
rightUpperLegKinematics(subjectID).position = rightUpperLegPosition;
rightUpperLegKinematics(subjectID).velocity = rightUpperLegVelocity;
rightUpperLegKinematics(subjectID).angularVelocity = rightUpperLegAngularVelocity;
rightUpperLegKinematics(subjectID).acceleration = rightUpperLegAcceleration;
rightUpperLegKinematics(subjectID).angularAcceleration = rightUpperLegAngularAcceleration;

rightLowerLegKinematics(subjectID).orientation = rightLowerLegOrientation;
rightLowerLegKinematics(subjectID).position = rightLowerLegPosition;
rightLowerLegKinematics(subjectID).velocity = rightLowerLegVelocity;
rightLowerLegKinematics(subjectID).angularVelocity = rightLowerLegAngularVelocity;
rightLowerLegKinematics(subjectID).acceleration = rightLowerLegAcceleration;
rightLowerLegKinematics(subjectID).angularAcceleration = rightLowerLegAngularAcceleration;

rightFootKinematics(subjectID).orientation = rightFootOrientation;
rightFootKinematics(subjectID).position = rightFootPosition;
rightFootKinematics(subjectID).velocity = rightFootVelocity;
rightFootKinematics(subjectID).angularVelocity = rightFootAngularVelocity;
rightFootKinematics(subjectID).acceleration = rightFootAcceleration;
rightFootKinematics(subjectID).angularAcceleration = rightFootAngularAcceleration;

rightToeKinematics(subjectID).orientation = rightToeOrientation;
rightToeKinematics(subjectID).position = rightToePosition;
rightToeKinematics(subjectID).velocity = rightToeVelocity;
rightToeKinematics(subjectID).angularVelocity = rightToeAngularVelocity;
rightToeKinematics(subjectID).acceleration = rightToeAcceleration;
rightToeKinematics(subjectID).angularAcceleration = rightToeAngularAcceleration;

leftUpperLegKinematics(subjectID).orientation = leftUpperLegOrientation;
leftUpperLegKinematics(subjectID).position = leftUpperLegPosition;
leftUpperLegKinematics(subjectID).velocity = leftUpperLegVelocity;
leftUpperLegKinematics(subjectID).angularVelocity = leftUpperLegAngularVelocity;
leftUpperLegKinematics(subjectID).acceleration = leftUpperLegAcceleration;
leftUpperLegKinematics(subjectID).angularAcceleration = leftUpperLegAngularAcceleration;

leftLowerLegKinematics(subjectID).orientation = leftLowerLegOrientation;
leftLowerLegKinematics(subjectID).position = leftLowerLegPosition;
leftLowerLegKinematics(subjectID).velocity = leftLowerLegVelocity;
leftLowerLegKinematics(subjectID).angularVelocity = leftLowerLegAngularVelocity;
leftLowerLegKinematics(subjectID).acceleration = leftLowerLegAcceleration;
leftLowerLegKinematics(subjectID).angularAcceleration = leftLowerLegAngularAcceleration;

leftFootKinematics(subjectID).orientation = leftFootOrientation;
leftFootKinematics(subjectID).position = leftFootPosition;
leftFootKinematics(subjectID).velocity = leftFootVelocity;
leftFootKinematics(subjectID).angularVelocity = leftFootAngularVelocity;
leftFootKinematics(subjectID).acceleration = leftFootAcceleration;
leftFootKinematics(subjectID).angularAcceleration = leftFootAngularAcceleration;

leftToeKinematics(subjectID).orientation = leftToeOrientation;
leftToeKinematics(subjectID).position = leftToePosition;
leftToeKinematics(subjectID).velocity = leftToeVelocity;
leftToeKinematics(subjectID).angularVelocity = leftToeAngularVelocity;
leftToeKinematics(subjectID).acceleration = leftToeAcceleration;
leftToeKinematics(subjectID).angularAcceleration = leftToeAngularAcceleration;

% Joint angles

jL5S1Angle(subjectID).jointAngle = jL5S1JointAngle;
jL5S1Angle(subjectID).jointAngleXZY = jL5S1JointAngleXZY;

jL4L3Angle(subjectID).jointAngle = jL4L3JointAngle;
jL4L3Angle(subjectID).jointAngleXZY = jL4L3JointAngleXZY;

jL1T12Angle(subjectID).jointAngle = jL1T12JointAngle;
jL1T12Angle(subjectID).jointAngleXZY = jL1T12JointAngleXZY;

jT9T8Angle(subjectID).jointAngle = jT9T8JointAngle;
jT9T8Angle(subjectID).jointAngleXZY = jT9T8JointAngleXZY;

jT1C7Angle(subjectID).jointAngle = jT1C7JointAngle;
jT1C7Angle(subjectID).jointAngleXZY = jT1C7JointAngleXZY;

jC1HeadAngle(subjectID).jointAngle = jC1HeadJointAngle;
jC1HeadAngle(subjectID).jointAngleXZY = jC1HeadJointAngleXZY;

jRightC7ShoulderAngle(subjectID).jointAngle = jRightC7ShoulderJointAngle;
jRightC7ShoulderAngle(subjectID).jointAngleXZY = jRightC7ShoulderJointAngleXZY;

jRightShoulderAngle(subjectID).jointAngle = jRightShoulderJointAngle;
jRightShoulderAngle(subjectID).jointAngleXZY = jRightShoulderJointAngleXZY;

jRightElbowAngle(subjectID).jointAngle = jRightElbowJointAngle;
jRightElbowAngle(subjectID).jointAngleXZY = jRightElbowJointAngleXZY;

jRightWristAngle(subjectID).jointAngle = jRightWristJointAngle;
jRightWristAngle(subjectID).jointAngleXZY = jRightWristJointAngleXZY;

jLeftC7ShoulderAngle(subjectID).jointAngle = jLeftC7ShoulderJointAngle;
jLeftC7ShoulderAngle(subjectID).jointAngleXZY = jLeftC7ShoulderJointAngleXZY;

jLeftShoulderJAngle(subjectID).jointAngle = jLeftShoulderJointAngle;
jLeftShoulderAngle(subjectID).jointAngleXZY = jLeftShoulderJointAngleXZY;

jLeftElbowAngle(subjectID).jointAngle = jLeftElbowJointAngle;
jLeftElbowAngle(subjectID).jointAngleXZY = jLeftElbowJointAngleXZY;

jLeftWristAngle(subjectID).jointAngle = jLeftWristJointAngle;
jLeftWristAngle(subjectID).jointAngleXZY = jLeftWristJointAngleXZY;

jRightHipAngle(subjectID).jointAngle = jRightHipJointAngle;
jRightHipAngle(subjectID).jointAngleXZY = jRightHipJointAngleXZY;

jRightKneeAngle(subjectID).jointAngle = jRightKneeJointAngle;
jRightKneeAngle(subjectID).jointAngleXZY = jRightKneeJointAngleXZY;

jRightAnkleAngle(subjectID).jointAngle = jRightAnkleJointAngle;
jRightAnkleJAngle(subjectID).jointAngleXZY = jRightAnkleJointAngleXZY;

jRightBallFootAngle(subjectID).jointAngle = jRightBallFootJointAngle;
jRightBallFootAngle(subjectID).jointAngleXZY = jRightBallFootJointAngleXZY;

jLeftHipAngle(subjectID).jointAngle = jLeftHipJointAngle;
jLeftHipAngle(subjectID).jointAngleXZY = jLeftHipJointAngleXZY;

jLeftKneeAngle(subjectID).jointAngle = jLeftKneeJointAngle;
jLeftKneeAngle(subjectID).jointAngleXZY = jLeftKneeJointAngleXZY;

jLeftAnkleAngle(subjectID).jointAngle = jLeftAnkleJointAngle;
jLeftAnkleAngle(subjectID).jointAngleXZY = jLeftAnkleJointAngleXZY;

jLeftBallFootAngle(subjectID).jointAngle = jLeftBallFootJointAngle;
jLeftBallFootAngle(subjectID).jointAngleXZY = jLeftBallFootJointAngleXZY;

fprintf('---------\n');
fprintf('End of extraction\n');


%% Plot

dataTime = linspace(1,nFrames,nFrames);

% Upper arm 

figUpperArmAcceleration = figure();
axes1 = axes('Parent',figUpperArmAcceleration,'FontSize',16);
box(axes1,'on');
hold(axes1,'on');
grid on;

subplot(2,2,1)
plot1 = plot(dataTime,rightUpperArmKinematics(subjectID).acceleration(:,1),'lineWidth',1.5); hold on;
set(plot1,'color',[0 0 1]);
plot2 = plot(dataTime,rightUpperArmKinematics(subjectID).acceleration(:,2),'lineWidth',1.5); hold on;
set(plot2,'color',[1 0.7 0]);
plot3 = plot(dataTime,rightUpperArmKinematics(subjectID).acceleration(:,3),'lineWidth',1.5); hold on;
set(plot3,'color',[1 0.2 0]);

title(sprintf('Right upperarm linear acceleration'));
leg = legend('$a_{x}$','$a_{y}$','$a_{z}$','Location','southeast');
set(leg,'Interpreter','latex');
set(leg,'FontSize',18);
xlabel('Frames','FontSize',20);
ylabel('Linear acceleration','FontSize',20);
axis tight;
grid on;

subplot(2,2,2)
plot1 = plot(dataTime,leftUpperArmKinematics(subjectID).acceleration(:,1),'lineWidth',1.5); hold on;
set(plot1,'color',[0 0 1]);
plot2 = plot(dataTime,leftUpperArmKinematics(subjectID).acceleration(:,2),'lineWidth',1.5); hold on;
set(plot2,'color',[1 0.7 0]);
plot3 = plot(dataTime,leftUpperArmKinematics(subjectID).acceleration(:,3),'lineWidth',1.5); hold on;
set(plot3,'color',[1 0.2 0]);

title(sprintf('Left upperarm linear acceleration'));
leg = legend('$a_{x}$','$a_{y}$','$a_{z}$','Location','southeast');
set(leg,'Interpreter','latex');
set(leg,'FontSize',18);
xlabel('Frames','FontSize',20);
ylabel('Linear acceleration','FontSize',20);
axis tight;
grid on;

subplot(2,2,3)
plot1 = plot(dataTime,rightUpperArmKinematics(subjectID).angularAcceleration(:,1),'lineWidth',1.5); hold on;
set(plot1,'color',[0 0 1]);
plot2 = plot(dataTime,rightUpperArmKinematics(subjectID).angularAcceleration(:,2),'lineWidth',1.5); hold on;
set(plot2,'color',[1 0.7 0]);
plot3 = plot(dataTime,rightUpperArmKinematics(subjectID).angularAcceleration(:,3),'lineWidth',1.5); hold on;
set(plot3,'color',[1 0.2 0]);

title(sprintf('Right upperarm angular acceleration'));
leg = legend('$\alpha_{x}$','$\alpha_{y}$','$\alpha_{z}$','Location','southeast');
set(leg,'Interpreter','latex');
set(leg,'FontSize',18);
xlabel('Frames','FontSize',20);
ylabel('Angular acceleration','FontSize',20);
axis tight;
grid on;

subplot(2,2,4)
plot1 = plot(dataTime,leftUpperArmKinematics(subjectID).angularAcceleration(:,1),'lineWidth',1.5); hold on;
set(plot1,'color',[0 0 1]);
plot2 = plot(dataTime,leftUpperArmKinematics(subjectID).angularAcceleration(:,2),'lineWidth',1.5); hold on;
set(plot2,'color',[1 0.7 0]);
plot3 = plot(dataTime,leftUpperArmKinematics(subjectID).angularAcceleration(:,3),'lineWidth',1.5); hold on;
set(plot3,'color',[1 0.2 0]);

title(sprintf('Left upperarm angular acceleration'));
leg = legend('$a_{x}$','$a_{y}$','$a_{z}$','Location','southeast');
set(leg,'Interpreter','latex');
set(leg,'FontSize',18);
xlabel('Frames','FontSize',20);
ylabel('Angular acceleration','FontSize',20);
axis tight;
grid on;

% Forearm 

figForeArmAcceleration = figure();
axes1 = axes('Parent',figForeArmAcceleration,'FontSize',16);
box(axes1,'on');
hold(axes1,'on');
grid on;

subplot(2,2,1)
plot1 = plot(dataTime,rightForeArmKinematics(subjectID).acceleration(:,1),'lineWidth',1.5); hold on;
set(plot1,'color',[0 0 1]);
plot2 = plot(dataTime,rightForeArmKinematics(subjectID).acceleration(:,2),'lineWidth',1.5); hold on;
set(plot2,'color',[1 0.7 0]);
plot3 = plot(dataTime,rightForeArmKinematics(subjectID).acceleration(:,3),'lineWidth',1.5); hold on;
set(plot3,'color',[1 0.2 0]);

title(sprintf('Right forearm linear acceleration'));
leg = legend('$a_{x}$','$a_{y}$','$a_{z}$','Location','southeast');
set(leg,'Interpreter','latex');
set(leg,'FontSize',18);
xlabel('Frames','FontSize',20);
ylabel('Linear acceleration','FontSize',20);
axis tight;
grid on;

subplot(2,2,2)
plot1 = plot(dataTime,leftForeArmKinematics(subjectID).acceleration(:,1),'lineWidth',1.5); hold on;
set(plot1,'color',[0 0 1]);
plot2 = plot(dataTime,leftForeArmKinematics(subjectID).acceleration(:,2),'lineWidth',1.5); hold on;
set(plot2,'color',[1 0.7 0]);
plot3 = plot(dataTime,leftForeArmKinematics(subjectID).acceleration(:,3),'lineWidth',1.5); hold on;
set(plot3,'color',[1 0.2 0]);

title(sprintf('Left forearm linear acceleration'));
leg = legend('$a_{x}$','$a_{y}$','$a_{z}$','Location','southeast');
set(leg,'Interpreter','latex');
set(leg,'FontSize',18);
xlabel('Frames','FontSize',20);
ylabel('Linear acceleration','FontSize',20);
axis tight;
grid on;

subplot(2,2,3)
plot1 = plot(dataTime,rightForeArmKinematics(subjectID).angularAcceleration(:,1),'lineWidth',1.5); hold on;
set(plot1,'color',[0 0 1]);
plot2 = plot(dataTime,rightForeArmKinematics(subjectID).angularAcceleration(:,2),'lineWidth',1.5); hold on;
set(plot2,'color',[1 0.7 0]);
plot3 = plot(dataTime,rightForeArmKinematics(subjectID).angularAcceleration(:,3),'lineWidth',1.5); hold on;
set(plot3,'color',[1 0.2 0]);

title(sprintf('Right forearm angular acceleration'));
leg = legend('$\alpha_{x}$','$\alpha_{y}$','$\alpha_{z}$','Location','southeast');
set(leg,'Interpreter','latex');
set(leg,'FontSize',18);
xlabel('Frames','FontSize',20);
ylabel('Angular acceleration','FontSize',20);
axis tight;
grid on;

subplot(2,2,4)
plot1 = plot(dataTime,leftForeArmKinematics(subjectID).angularAcceleration(:,1),'lineWidth',1.5); hold on;
set(plot1,'color',[0 0 1]);
plot2 = plot(dataTime,leftForeArmKinematics(subjectID).angularAcceleration(:,2),'lineWidth',1.5); hold on;
set(plot2,'color',[1 0.7 0]);
plot3 = plot(dataTime,leftForeArmKinematics(subjectID).angularAcceleration(:,3),'lineWidth',1.5); hold on;
set(plot3,'color',[1 0.2 0]);

title(sprintf('Left forearm angular acceleration'));
leg = legend('$a_{x}$','$a_{y}$','$a_{z}$','Location','southeast');
set(leg,'Interpreter','latex');
set(leg,'FontSize',18);
xlabel('Frames','FontSize',20);
ylabel('Angular acceleration','FontSize',20);
axis tight;
grid on;

% Hand 

figHandAcceleration = figure();
axes1 = axes('Parent',figHandAcceleration,'FontSize',16);
box(axes1,'on');
hold(axes1,'on');
grid on;

subplot(2,2,1)
plot1 = plot(dataTime,rightHandKinematics(subjectID).acceleration(:,1),'lineWidth',1.5); hold on;
set(plot1,'color',[0 0 1]);
plot2 = plot(dataTime,rightHandKinematics(subjectID).acceleration(:,2),'lineWidth',1.5); hold on;
set(plot2,'color',[1 0.7 0]);
plot3 = plot(dataTime,rightHandKinematics(subjectID).acceleration(:,3),'lineWidth',1.5); hold on;
set(plot3,'color',[1 0.2 0]);

title(sprintf('Right hand linear acceleration'));
leg = legend('$a_{x}$','$a_{y}$','$a_{z}$','Location','southeast');
set(leg,'Interpreter','latex');
set(leg,'FontSize',18);
xlabel('Frames','FontSize',20);
ylabel('Linear acceleration','FontSize',20);
axis tight;
grid on;

subplot(2,2,2)
plot1 = plot(dataTime,leftHandKinematics(subjectID).acceleration(:,1),'lineWidth',1.5); hold on;
set(plot1,'color',[0 0 1]);
plot2 = plot(dataTime,leftHandKinematics(subjectID).acceleration(:,2),'lineWidth',1.5); hold on;
set(plot2,'color',[1 0.7 0]);
plot3 = plot(dataTime,leftHandKinematics(subjectID).acceleration(:,3),'lineWidth',1.5); hold on;
set(plot3,'color',[1 0.2 0]);

title(sprintf('Left hand linear acceleration'));
leg = legend('$a_{x}$','$a_{y}$','$a_{z}$','Location','southeast');
set(leg,'Interpreter','latex');
set(leg,'FontSize',18);
xlabel('Frames','FontSize',20);
ylabel('Linear acceleration','FontSize',20);
axis tight;
grid on;

subplot(2,2,3)
plot1 = plot(dataTime,rightHandKinematics(subjectID).angularAcceleration(:,1),'lineWidth',1.5); hold on;
set(plot1,'color',[0 0 1]);
plot2 = plot(dataTime,rightHandKinematics(subjectID).angularAcceleration(:,2),'lineWidth',1.5); hold on;
set(plot2,'color',[1 0.7 0]);
plot3 = plot(dataTime,rightHandKinematics(subjectID).angularAcceleration(:,3),'lineWidth',1.5); hold on;
set(plot3,'color',[1 0.2 0]);

title(sprintf('Right hand angular acceleration'));
leg = legend('$\alpha_{x}$','$\alpha_{y}$','$\alpha_{z}$','Location','southeast');
set(leg,'Interpreter','latex');
set(leg,'FontSize',18);
xlabel('Frames','FontSize',20);
ylabel('Angular acceleration','FontSize',20);
axis tight;
grid on;

subplot(2,2,4)
plot1 = plot(dataTime,leftHandKinematics(subjectID).angularAcceleration(:,1),'lineWidth',1.5); hold on;
set(plot1,'color',[0 0 1]);
plot2 = plot(dataTime,leftHandKinematics(subjectID).angularAcceleration(:,2),'lineWidth',1.5); hold on;
set(plot2,'color',[1 0.7 0]);
plot3 = plot(dataTime,leftHandKinematics(subjectID).angularAcceleration(:,3),'lineWidth',1.5); hold on;
set(plot3,'color',[1 0.2 0]);

title(sprintf('Left hand angular acceleration'));
leg = legend('$a_{x}$','$a_{y}$','$a_{z}$','Location','southeast');
set(leg,'Interpreter','latex');
set(leg,'FontSize',18);
xlabel('Frames','FontSize',20);
ylabel('Angular acceleration','FontSize',20);
axis tight;
grid on;

